### PR TITLE
Milestone1: Bookstore initialize project with components

### PR DESCRIPTION
**Pull request by Chandan-devs-tech**
# In this milestone 

- Setup a new React application using [Create React App](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app)
- Created a directory for reusable components `/components`
- Installed [React Router V6](https://reactrouter.com/en/main/start/tutorial#setup)
[Setup router](https://reactrouter.com/en/main/start/tutorial#adding-a-router) inside of `<App>`
- Added 2 routes in my application, each should render a page component:
  - `/`
  - `/categories`
- Created components inside of the `/components `directory:
  - Contains individual book state, as well as a button to delete the book
  - Contains a list to renders individual books
  - Contains a form to create new books
  - Contains a navigation to link to the 2 routes that I created

### CODE REVIEW

**Comment by topeogunleye** [comment]
@Chandan-devs-tech, Great job on the changes made. please can you update your README file to use the [Microverse template](https://github.com/microverseinc/readme-template)?

**Comment by Chandan-devs-tech** [comment]
> @Chandan-devs-tech, Great job on the changes made. please can you update your README file to use the [Microverse template](https://github.com/microverseinc/readme-template)?

**Comment by topeogunleye** [comment]
> > @Chandan-devs-tech, Great job on the changes made. please can you update your README file to use the [Microverse template](https://github.com/microverseinc/readme-template)?

@Chandan-devs-tech, Please reopen the branch

**Review by topeogunleye — APPROVED** [review]
### **STATUS: APPROVED  ✔️** 
------
Hi @Chandan-devs-tech,  

Overall, your project demonstrates a solid understanding of React and React Router concepts. Your code is clean, well-organized, and follows best practices. Keep up the excellent work! 😊 If you have any questions or need further assistance, feel free to ask. Happy coding! 🎉👍! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟

wiserhood-cheers

## To highlight :champagne: 
🚀 Code Review Summary 🚀

Great job on your project! You've fulfilled the project requirements effectively. 👏 The code is well-structured and follows the necessary standards. Here are the highlights:

1. Project Initialization: ✔️ You correctly used Create React App to set up your project, ensuring a standardized and reliable development environment.

2. React Router Setup: ✔️ You successfully implemented React Router in your `<App>` component, allowing smooth navigation within the app. The navigation links in `<Navbar>` to "/" and "/categories" are functioning correctly.

3. Page Components: ✔️ You created two page components, `<Books>` and `<Categories>`, which provide a clean and modular structure to your project.

4. <Books> Component: ✔️ Your implementation of the `<Books>` component is well-organized and adheres to the requirements. The <BookList> component effectively renders a list of books using the <Book> component. The <Book> component takes book data as a prop and properly displays the book's title and author. Additionally, the "Remove" button placeholder provides a clear intention for future development.

5. <NewBookForm> Component: ✔️ You've implemented the <NewBookForm> component as required, providing a form with inputs for the title and author of the book. The form's "Submit" button placeholder indicates your intent for future additions.

## [Optional] suggestions:
 * Nothing to mention.

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear
Please, remember to tag @topeogunleye in your question so I can receive the notification

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
